### ISSUE TITLE
Compressed or uncompressed point encoding?

### ISSUE THREAD

**Issue by alxdavids** [cfrg/draft-irtf-cfrg-voprf#101]
Should we support both, or just one?

**Comment by chris-wood** [comment]
Let's pick only one per ciphersuite, and let's be consistent across ciphersuites. I prefer the uncompressed format, if only because that's what other standards tend to use (TLS, HPKE, etc).

**Comment by alxdavids** [comment]
We'll go with compressed based on conversation, will change sage serialization code.
