### ISSUE TITLE
Deserialization can fail

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#109]
Warn the reader that deserialization can return error if the input bytes does not correspond to a valid group element.

**Comment by alxdavids** [comment]
Not sure we need this caveat because SEC1/RFC7748 defines the correct syntax for serialization. If you deviate from this syntax then you're not compliant. What do you think @chris-wood?

**Comment by armfazh** [comment]
I think what is missing is alerting the reader/implementor that deserialization can fail, and if this happen, the protocol cannot continue.

**Comment by alxdavids** [comment]
I take it to mean, if you're not compliant with everything in the doc (including refs), then the protocol will fail. In my opinion, this can be left implicit.
