### ISSUE TITLE
Unifying pseudo-code style

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#110]
1 ) There are many functions following an object-oriented design, I don't know if this helps as the only "object" is GG.

2) The style of pseudo-code is sometimes python, other times Go/rust, I consider is better to use C-style pseudo-code. 

3) Enumeration of substeps, for example:

~~~
 4.     if x = 0 
 4.1        foo()
 4.2        foo() 
 5.     bar() 
~~~

**Comment by alxdavids** [comment]
Would you be able to highlight some particular examples for where you are thinking things should change? It's not exactly clear to me what you are referring to with these points? FWIW, I'm not super worried about the pseudocode at the moment, I think it's clear enough.

**Comment by armfazh** [comment]
This issue is not one of the higher relevance, but still it could be difficult to grasp for someone who never coded in modern languages. It's is desired that specification be easy to read for anyone.  

Loops
``` 3. for i = 0 to m:```  vs ``` 2. for i in 1..m:```

The first is go/rust syntax, while the second one is more similar to C structs.
`Ev = Evaluation{ elements: elements }` and `2. Ev.proof = proof`

the `elements` starts empty.

```
1. elements = []
2. for i in 1..m:
    2.3. elements[i] = GG.Serialize(Z)
```

**Comment by chris-wood** [comment]
The change in #122 makes an attempt at clarity.
