### ISSUE TITLE
Bits indicating verifiablity support

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#113]
> Both participants also provide a boolean input vv and vp for the Client and Server respectively.  These boolean values should be equal, and correspond to whether the protocol is executed with verifiability intended, or not. In other words, whether the functionality computes an OPRF protocol (vv = vp = 0), or a VOPRF protocol (vv = vp = 1). If vv = 1 && vp = 0, then the protocol will abort in Unblind when the client attempts to verify the zero-knowledge proof.

I think the bits are not required since they come from the ciphersuite definition, so they are constant domain parameters.

**Comment by alxdavids** [comment]
This is true, but I think we'll need to then pass around ciphersuite identifiers into the algorithms so we can check this?

**Comment by alxdavids** [comment]
Okay I've just removed them and replaced with a global `verifiable` variable
