### ISSUE TITLE
Section 4.3 uses undefined values

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#115]
Section 4.3 is difficult to understand as there are many undefined variables. The protocol data-flow looks clean and simple, however there are many variables that are not stated its purpose nor its domain.

**Comment by alxdavids** [comment]
Do you mean in the diagram? This is all explained in the following section. I guess we could move the protocol to after the algorithm descriptions though? What do you think @chris-wood? I personally prefer to have it this way around to put more emphasis on the protocol data flow and not worry so much about the algorithm implementation.

**Comment by chris-wood** [comment]
I agree -- I think having the protocol flow abstraction up front helps.

**Comment by alxdavids** [comment]
Okay, let's leave it as it is for now.
