### ISSUE TITLE
Definition of H2

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#116]
H2 might be better defined as H2(x) = OS2IP(H(x)) mod p. 
This avoids rejection sampling on Section 5.3

**Comment by alxdavids** [comment]
Doesn't this introduce bias if you get a value that's greater than p?

**Comment by chris-wood** [comment]
We should just use hash-to-field from the hash-to-curve document (for all groups considered). I don't see why we'd reinvent the wheel here. :-)

**Comment by armfazh** [comment]
> We should just use hash-to-field from the hash-to-curve document (for all groups considered). I don't see why we'd reinvent the wheel here. :-)

Agree
