### ISSUE TITLE
Inconsistencies in Evaluate pseudo-code

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#124]
https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/73492d2727115a7591a3d340e31f0565465348a7/draft-irtf-cfrg-voprf.md#L662-L675

1) Why `Ev` is passed as input to `Evaluate`?
2) Why `Ev` is passed to `generate_proof`, if it wasn't constructed yet?

**Comment by chris-wood** [comment]
Good catch - it shouldn't be. Can you please remove that in your PR?

**Comment by armfazh** [comment]
Ok, I can work on that fix.
