### ISSUE TITLE
Undefined x variable

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#126]
What is `x` in these functions?

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/73492d2727115a7591a3d340e31f0565465348a7/draft-irtf-cfrg-voprf.md#L784-L786

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/73492d2727115a7591a3d340e31f0565465348a7/draft-irtf-cfrg-voprf.md#L1415-L1417

**Comment by alxdavids** [comment]
Should be `inputs[i]`

**Comment by chris-wood** [comment]
I fixed this with a direct push to master.
