### ISSUE TITLE
Include SerializedScalar type

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#139]
There is a distinction between group elements (a point on the curve) and serialized elements (its compact representation).
Analogously, we can refer as SerializedScalar to the short (mod p) representation of an integer scalar.

todo(armfazh): I can create a PR to the draft for this request.

**Comment by chris-wood** [comment]
I'm not sure I see the benefit of having this type, but let's see what the PR looks like.

**Comment by alxdavids** [comment]
I'm also not sure that we need this, I think we can move between the representations without being too descriptive for scalars.

**Comment by armfazh** [comment]
After thinking more on it, it's not necessary.
