### ISSUE TITLE
Use a draft-specific placeholder DST string

### ISSUE THREAD

**Issue by davidben** [cfrg/draft-irtf-cfrg-voprf#143]
If folks deploy experimental systems using VOPRF drafts, the fact that the DST uses "RFCXXXX" might break domain separation between drafts. HPKE used to use the same placeholder but switched to "HPKE-05", etc., with an RFC editor note:

> [[RFC editor: please change "HPKE-05" to "RFCXXXX", where XXXX is the final number, before publication.]]

See https://github.com/cfrg/draft-irtf-cfrg-hpke/pull/138.

Perhaps VOPRF should do something similar here.

**Comment by claucece** [comment]
Agreed. Should it be changed @chris-wood ?

**Comment by alxdavids** [comment]
This changes makes sense to me.
