### ISSUE TITLE
hashInput in Finalize and VerifyFinalize missing I2OSP calls

### ISSUE THREAD

**Issue by davidben** [cfrg/draft-irtf-cfrg-voprf#146]
hashInput in Finalize and VerifyFinalize is computed as:

```
  hashInput = len(token.data) || token.data ||
              len(issuedToken) || issuedToken ||
              len(info) || info ||
              len(finalizeDST) || finalizeDST
  return Hash(hashInput)
```

But the lengths are integers, not byte strings. I assume this was intended to say `I2OSP(len(...), ???)`. Given h1Input is also passed directly to Hash in ComputeComposites, I guess the lengths should all be two bytes, to be consistent.

```
  h1Input = I2OSP(len(gen), 2) || gen ||
            I2OSP(len(pkS), 2) || pkS ||
            I2OSP(len(blindTokens), 2) || blindTokens ||
            I2OSP(len(elements), 2) || elements ||
            I2OSP(len(seedDST), 2) || seedDST
  seed = Hash(h1Input)
```

Though it's worth noting that injectivity here depends on the DSTs being suffix-free, or on *all* the length prefixes having the same size. If, say, hashInput used `I2OSP(len(token.data), 4)`, hashInput and h1Input would no longer be injective for all possible values here. (Ignoring the part where DSTs in this document are suffix-free.)

This reminds of https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve/issues/236. (Hrm... do we care about domain separation between the hash calls here and those inside hash-to-curve? That might suggest the DST constructions should match. Although that is really a theoretical issue since the DSTs are indeed suffix-free.)

**Comment by claucece** [comment]
Yes, I agree on this. I see no place, also, where a different length will be used other than `I2OSP(len(x), 2)`

**Comment by chris-wood** [comment]
I fixed this directly on master.
