### ISSUE TITLE
Necessary to serialize generator?

### ISSUE THREAD

**Issue by davidben** [cfrg/draft-irtf-cfrg-voprf#147]
GenerateProof incorporates `gen = GG.Serialize(G)` into the HashToScalar call, but the context string already includes the cipher suite ID, which covers all the common parameters, notably the generator. It seems to me that can be omitted.

**Comment by claucece** [comment]
Mmm.. while true that through that the context string contains the suite.ID, this is only an id value, although it indeed recognises the suite. But I don't think the generator was included as a parameter for `HashToScalar` to recognise the suite, but rather to differentiate the hash. 

I'm not sure why it was historically introduced.. maybe @chris-wood , @alxdavids or @armfazh will know.

**Comment by davidben** [comment]
Right, I thought all that needed there was for different suites' hash invocations to use different inputs. The suite is identified by ID, which is hashed, and the generator is specified by the suite, so it seems the generator is covered. 

(Disclaimer: I don't actually know how the formal analyses work, so my intuition could just be totally wrong. :-) )

**Comment by armfazh** [comment]
According to the specification [link](https://github.com/privacypass/challenge-bypass-extension/blob/master/docs/PROTOCOL.md#nizk-proofs-of-discrete-log-equality), the pair (G,Y) must be maintained.

**Comment by davidben** [comment]
Isn't that just a question of whether you believe the pre-agreed parameters are GG or (GG, G). If you believe even GG weren't pre-agreed, I imagine H_3 would need to pass the group in. And when we give a name to an EC group, it typically comes with a pre-agreed generator.

Put another way, you could define H_3 from the specification as H_3(G,Y,M,Z,A',B') =
- If G == standard_G, return HashToScalar(code_point || Y || M || Z || A' || B')
- Else, return HashToScalar(code_point2 || G || Y || M || Z || A' || B')

This is a perfectly injective encoding, as long as we can pick some distinct throwaway code_point2 value. And then you observe that you never hit the second case so we don't need to write it down.
