### ISSUE TITLE
Can we remove the 'Addition' field on every ciphersuite?

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-voprf#151]
The 'Addition' field on every ciphersuite is always the same:

```
  - Addition: Adding curve points directly corresponds to the group
    addition operation.
```

we could perhaps remove it, as it is generally defined on the preliminaries.

**Comment by alxdavids** [comment]
Yeah, we should refactor this out as a common operator for each ciphersuite
