### ISSUE TITLE
Allow server context creation with external key pair

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#168]
In some cases it's useful to use a pre-existing key pair for a server context. Currently, keys are generated inline (in SetupBaseServer, for example). We should fix that.

**Comment by armfazh** [comment]
The purpose of Setup is to generate keys and domain parameters, and this should run once during the _offline_ phase of the protocol.
There is no inline generation during the _online_ phase of the protocol.Hence, I think the specification is right.

-- If needed, we could add a line saying: "users can use pre-existing keys provided that keys were generated using a compatible  procedure as the one described in Setup".

**Comment by chris-wood** [comment]
> -- If needed, we could add a line saying: "users can use pre-existing keys provided that keys were generated using a compatible procedure as the one described in Setup".

This is precisely the idea! It's definitely needed for OPAQUE.
