### ISSUE TITLE
Issues in Additive mode

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-voprf#195]
When blinding in Additive mode, it says to store the blinded public key (which is a Point/Element) in the Token structure:

```
token = Token{
    data: input,
    blind: preproc.blindedPublicKey
  }
```

But the token structure is defined as taking a scalar, not a point/element as blinding element:

```
struct {
  opaque data<1..2^16-1>;
  Scalar blind<1..2^16-1>;
} Token;
```

There also seems to be no need of storing the `preproc.blindedPublicKey` in `blind`.

**Comment by chris-wood** [comment]
Great catch! I don't think the additive section has been kept up to date very well. Let's revisit and address this issue soon.

**Comment by chris-wood** [comment]
@claucece, I think this is resolved now that #190 is merged. Can you please confirm, and close if so?

**Comment by bytemare** [comment]
Getting rid of the Token structure altogether solves the issue, indeed 👍😃

**Comment by chris-wood** [comment]
Closing as resolved. @claucece, please re-open if this still needs to be fixed!
