### ISSUE TITLE
Scalar structure is not clearly defined

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-voprf#196]
The `Scalar` structure is first used on the `Data Structures` section, and not previously defined, and it is used as: 
`Scalar blind<1..2^16-1>;`, which seems to imply this is the serialized scalar.

It is later defined as:
`This document uses the types Element and Scalar to denote elements of the group GG and its underlying scalar field GF(p), respectively.`, which seems to imply it is the underlying reprensentation.

It is not clear what it is referred to.

**Comment by chris-wood** [comment]
I think we should just say `Scalar` refers to an actual scalar element for the group. It seems the only time we need to serialize and send a scalar on the wire is for the proof, so we can have a `SerializedScalar` type (similar to `SerializedElement`) for that.

**Comment by armfazh** [comment]
Similar to #139

**Comment by chris-wood** [comment]
@claucece, can we close this now that #190 is merged?

**Comment by chris-wood** [comment]
Closing as resolved. @claucece, please re-open if this still needs to be fixed!
