### ISSUE TITLE
Serialized elements and scalars should be fixed-length

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#197]
Currently, serialized things are variable length. There's no real reason they need to be variable length, and doing so just complicates implementations. Let's make them *both* fixed length.

**Comment by bytemare** [comment]
Hello,

doesn't the serialized length depend on the cipher suite they are from? p-256 and p-521 points don't have the same length when encoded.

**Comment by chris-wood** [comment]
It does, yes. The fixed length would depend on the underlying group,

**Comment by chris-wood** [comment]
Fixed in #190.
