### ISSUE TITLE
Blind in PreprocessedBlind

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-voprf#199]
Hello,

the blind element used for preprocessing is not used after generating the client's own public key (i.e. scalar multiplication with the generator/base point) and blinding the server public key, but is still contained within the PreprocessedBlind structure.

I suppose this is useful for debugging purposes, and thus implementation dependant. In this case, it might be useful to mention in the draft. Is my understanding correct ?

Thanks

**Comment by chris-wood** [comment]
Good catch :-) I removed this from the `Preprocess` output [here](https://github.com/cfrg/draft-irtf-cfrg-voprf/commit/87d42c249e83cce10a741e4a7bc96486e8b6cdf1). Closing as resolved!
