### ISSUE TITLE
Clarifications on BatchedEvaluation

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-voprf#201]
Hello,

reading the latest version of the draft, there are very few explanations about batching inputs/evaluations. For the reader unfamiliar with the subject it is not clear what these are about.

From what I understand from a conversation with @chris-wood:
the mechanism works in a situation where a client requests multiple evaluations and could do it by sending all blinded inputs at once. The server would then evaluate them all but have a single proof for them all, and send this single proof back with the individual evaluations.
So, for N blinded inputs from the client, instead of having N requests, N evaluations, N proofs, and N responses, we would bring that down to  1 proof and 1 request-response carrying the N blinded inputs and N evaluations.

Is this correct?

**Comment by chris-wood** [comment]
That's correct! @bytemare, if you have cycles, would you mind creating a PR with this suggested clarification?

**Comment by bytemare** [comment]
Thanks! Yes, I think I can do that in the following days.

**Comment by bytemare** [comment]
I tried to interpret it given the new test vectors.

I think the draft could need a dedicated section about Batching to address the following points:

1. Blinding method
State that batching is only available with multiplicative binding for the client since we're using multiple blinds, a dedicated one for each input. Except if the logic changes and enables blinding using the preprocessed values with additive blinding. (I don't see an immediate reason why this won't be possible)
2. Mode
Why is batching only used in verifiable mode? A client could rightfully ask for a batch of evaluations in base mode.
3. Client and Server API
The client and server behaviors are impacted and the function specs would need to be added. This is in already in part addressed for the server.
There could be different functions or the same but all accept an array of arguments and the 'simple' blinding would only use the first element.

Notes:
- orders MUST be preserved, or unblinding will not have the desired result.
- rate-limiting / anti-dos must be implemented by higher-level applications.

**Comment by chris-wood** [comment]
> Blinding method. State that batching is only available with multiplicative binding for the client since we're using multiple blinds, a dedicated one for each input. Except if the logic changes and enables blinding using the preprocessed values with additive blinding.

Hmm, I'm not sure I follow this. What "logic changes" are required to allow additive blinding for batches? 

> Mode. Why is batching only used in verifiable mode? A client could rightfully ask for a batch of evaluations in base mode.

In base mode, each blinded element sent to the server yields one evaluated element in response. Unless I'm missing something, there's no efficiency to be gained by batching in this case. But maybe you have something particular in mind?

> Client and Server API. The client and server behaviors are impacted and the function specs would need to be added. This is in already in part addressed for the server. There could be different functions or the same but all accept an array of arguments and the 'simple' blinding would only use the first element.

To be clear, are you suggesting that the client API be augmented to use batching by default, or something else? (I don't disagree that some clarifications or changes are needed, but what's less clear to me is what should be the default.)

> orders must be preserved, or unblinding will not have the desired result.

This is definitely something that's important to note, yeah.

**Comment by bytemare** [comment]
> Hmm, I'm not sure I follow this. What "logic changes" are required to allow additive blinding for batches?

Not much actually, just that all inputs will be blinded with the same pre-computed element. I think I got confused since the test vectors imply using the multiplicative blinding. 

> In base mode, each blinded element sent to the server yields one evaluated element in response. Unless I'm missing something, there's no efficiency to be gained by batching in this case. But maybe you have something particular in mind?

Yes, benefits would be on the network level and avoiding to have N round trips if one has N inputs to evaluate. What do you think?

> To be clear, are you suggesting that the client API be augmented to use batching by default, or something else? (I don't disagree that some clarifications or changes are needed, but what's less clear to me is what should be the default.)

I don't know. It could indeed be easier to have one function/method for single blinding, and another one for batched blinding, that simply wraps the other (and would also support a batch with only a single input). This way, higher-level protocols would need to figure out which one to use depending on their needs. Having one entry point may lead to unnecessary complexity internally and for users. I'm just spitballing here. What do you think?
