### ISSUE TITLE
Add h2c DST in test vectors

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-voprf#215]
I suggest adding the DST used for hash-to-group and hash-to-scalar in the test vectors, just like info. This would allow identifying the correct assembly of that DST before trying to hash anything and fail early.

Since I can't install Sage on my working machine right now, here is the suggested line I think would allow this to be added.

test_oprf.sage, line 121
``` 
vecSuite["skSm"] = to_hex(group.serialize_scalar(server.skS))
+ vecSuite["dst"] = to_hex(_as_bytes("VOPRF06-HashToGroup-") + I2OSP(self.mode, 1) + I2OSP(self.suite.identifier, 2) )
if self.mode == mode_verifiable:
```

**Comment by chris-wood** [comment]
Thanks, @bytemare! We'll see if we can work this in.

**Comment by chris-wood** [comment]
@armfazh, what do you think about this?

**Comment by armfazh** [comment]
I don't think is needed at all (there is nothing special other with it),
however, if that helps to programmers to test code, then it may be worth add it in json files only.
