### ISSUE TITLE
Consider folding Unblind and Finalize together

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#219]
Currently, clients implement `Unblind` and `Finalize` together to complete the OPRF evaluation. I don't see a compelling reason to keep these separate, and expose an `Unblind` API, since it's not useful to OPRF clients. (They should not ever need the "intermediate" OPRF value -- the unblinded, evaluated elements.) I suggest we fold `Unblind` into `Finalize`. 

@armfazh, @alxdavids, @claucece: what do you think?

**Comment by claucece** [comment]
Agreed.

**Comment by armfazh** [comment]
iirc, privacy pass stores those intermediate tokens before redeemption. 
I don't know if that was done as an storage optimization. Alex knows better.

**Comment by chris-wood** [comment]
It appears to be done because the redemption API is what provides the `Finalize()` aux/info parameter. So one can fetch a token and then later redeem it for a given context. That's a reasonable design choice, so I'm going to close this as-is.

**Comment by armfazh** [comment]
> ... later redeem it for a given context

So that means to get generic pases/tokens, and then narrow them to a particular application/context with the aux parameter. That's interesting.
