### ISSUE TITLE
Consider adding no-DLEQ ciphersuite for VOPRF

### ISSUE THREAD

**Issue by alxdavids** [cfrg/draft-irtf-cfrg-voprf#225]
The PMB Tokens paper constructs a weaker version of a VOPRF without DLEQ proofs (see Section 7 of https://eprint.iacr.org/2020/072). The weakness of the construction allows the server to send back random garbage and the client cannot distinguish.

This effectively provides the server with an extra bit of privacy that it can remove. However, removing the DLEQ proofs also comes with the benefit of removing some of the more expensive computation from the server, so I think it should be considered as a separate ciphersuite. Note, this is only valid for the VOPRF in the additive blinding case.

First raised by @siyengar. cc @chris-wood, @armfazh, @claucece for further discussion.

**Comment by bytemare** [comment]
I may be misunderstanding, but OPAQUE is defined to use the non-verifiable OPRF, so already without any specific overhead. What would be the advantage ?

**Comment by chris-wood** [comment]
Given that this possibly worsens the privacy posture of the protocol and is limited to a particular implementation of the blinding step, I'm not inclined to make this change. @siyengar, can you elaborate on the benefit here? (I probably just didn't understand the motivation.)

**Comment by siyengar** [comment]
Ya it likely does worsen the privacy posture, although this is probably a bit more complicated as there are some issues with the current scheme as well if the client fails to perform proper validation. My thought on the benefits of this type of scheme were 3 fold:

1. Gets rid of the client needing to perform a validation step. As we know from TLS and other protocols, adding an `if` condition to the protocol allows people not to execute that `if` condition. And if people don't execute the proof then that also reduces the privacy of the protocol.
2. Reduces number of bytes needed to be downloaded from the server. You don't need to download an extra dleq proof step with this. 
3. A More intuitive protocol. You get a token and then replay the token, so it becomes an intuitively simpler protocol.

**Comment by chris-wood** [comment]
I don't disagree with any of the points, but I really don't understand the proposal. Cold you or @alxdavids whip up a draft PR with something more concrete?

**Comment by chris-wood** [comment]
Okay, I RTFM :-) this seems less like a new ciphersuite and more like a new mode because (a) the group doesn't matter, (b) implementation details differ compared to the other two modes, and (c) the security properties are different. Perhaps we could call this "WeakVerifiable" mode, or something? It might look like so:

1. Blind is as specified in Section 7 of [the PMB paper](https://eprint.iacr.org/2020/072.pdf).
2. Evaluate is as specified in the base mode.
3. Finalize is as specified in Section 7 of the PMB paper.  

I'll take this and put up a PR tomorrow. Maybe we can land this before the draft deadline on Monday.

**Comment by chris-wood** [comment]
Given that this particular variant requires some additional analysis, and it can be done in a followup spec should one want it, closing as WONTFIX. @siyengar, we can spin up a separate document should it really be needed.
