### ISSUE TITLE
Remove `info` parameter

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#226]
Finalize currently allows clients to provide mix in some application-layer info into the PRF evaluation. Is there any reason why we can't mix this in earlier in the protocol, e.g., alongside the application input? It's not cryptographically bound to the OPRF, and the client can use it to tweak the the output as they please. More specifically, they can acquire an OPRF evaluation and then Finalize it multiple times. I'm not sure I see the advantage of this, since it allows the verifier to link multiple Finalize outputs to the same sender. If a client truly wants N Finalize outputs, without sacrificing linkability, it seems they'd run the protocol N times. 

Given this, I propose we remove the `info` entirely. We have language that says clients should use this as a DST, but it's also possible to add domain separation to the *input*, e.g., by encoding `x` with a DST. This would simplify the API and remove a possible client footgun. 

What do you think, @alxdavids, @armfazh?

cc @jedisct1, too, in case he has thoughts on this!

**Comment by alxdavids** [comment]
@chris-wood Are you suggesting then that we place `info` in the final hash evaluation with a permanent fixed string? I don't really have any problem with this proposal, and I think it makes sense to remove any unneeded variability from this final step.

**Comment by chris-wood** [comment]
I’m thinking we remove it entirely.

**Comment by jedisct1** [comment]
No objections at all, especially since it will simplifies the API a bit.

**Comment by bytemare** [comment]
Agreed !

**Comment by armfazh** [comment]
Another option that might work is to remove `aux` from Finalize, and add it to Blind. Thus, Blind will hash both `input` and `aux` to obtain a point. So, we can maintain the `aux` as a domain separation string.

**Comment by chris-wood** [comment]
> Another option that might work is to remove aux from Finalize, and add it to Blind. Thus, Blind will hash both input and aux to obtain a point. So, we can maintain the aux as a domain separation string.

I'm not sure I see the benefit of having two string parameters with the same "properties" as input to the API. I'd prefer we give guidance for how applications can construct input with domain separation. (Or how implementations can bake domain separation beneath the API.)
