### ISSUE TITLE
Consider adding deterministic KeyGen function

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#228]
We currently assume the existence of a randomized `KeyGen` function for each of the groups we care about. There are some use cases where one might want to deterministically derive a key (pair) from a seed of appropriate entropy. @alxdavids, what do you think about adding this to the spec?

**Comment by chris-wood** [comment]
One way we might do this is by defining a mechanism based on HashToScalar() and a fixed generator for the group. @alxdavids, @armfazh: what do you think about adding a `Generator()` function to the POG API? We assume `ScalarBaseMult()` exists (for additive blinding), so this promoting `Generator()` to the API seems somewhat reasonable to me.

**Comment by armfazh** [comment]
The easiest way is to add an additional requirement to the group: to have a `KeygenFromSeed(seed)`.
So each group can define how to instantiate this function.

However, the motivation for adding this function is on the caller protocol. For OPRF, a server can expect to have its private key generated somehow by another entity (provided is a correct key, of course). So the caller protocol can assume the group has deterministic generation of keys, sample one, and pass it to OPRF-Server.
thougths?

**Comment by chris-wood** [comment]
> The easiest way is to add an additional requirement to the group: to have a KeygenFromSeed(seed).

I like this less because it introduces a new API, whereas the proposal above was to basically clarify what already exists. (We have HashToScalar and ScalarBaseMult, which should be sufficient, right?) 

> So the caller protocol can assume the group has deterministic generation of keys, sample one, and pass it to OPRF-Server.

This isn't quite the use case. The idea motivation for this change is to allow the "caller protocol" provides the seed to produce a key pair. How that's possible right now is not clearly defined.

**Comment by armfazh** [comment]
Actually, Keygen is not even defined in Section 2. Its first reference is at Sec 3.2.
`Prior to this phase, keys (skS, pkS) should be generated by calling a KeyGen function.`

So, defining `KeyGen()` and `KeyGen(seed)` at section 2.1 must be enough.

Q: do we assume the deterministic method exists, or do we specify it?

I think, we can only suggest how to implement the deterministic method, because there could be a different deterministic method to generate valid keys.

**Comment by chris-wood** [comment]
> I think, we can only suggest how to implement the deterministic method, because there could be a different deterministic method to generate valid keys.

Hmm, I don't think this is a viable solution, since users of this function should expect them to be interoperable. For example, two different implementations of the function should expect that KeyGen(seed) (or whatever) produces the same key, right?

**Comment by armfazh** [comment]
I agree. My main observation is whether the description of  Keygen(seed) is MUST or RECOMMENDED (according to the IETF definitions).

**Comment by chris-wood** [comment]
Ahh, okay, I see. I’m considering a MUST, given that it’s effectively part of the POG API.
