### ISSUE TITLE
HashTo* dst too short

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-voprf#244]
The new dst ( "HashToScalar-" + context )  for _HashTo-something_ operations is less than the 16 bytes recommended by h2c. A couple of more characters should fix this.

cc @chris-wood

**Comment by armfazh** [comment]
I think this was already addressed.

Note that the DST have more than 16 bytes:
DST for HashToGroup(): `DST = "HashToGroup-" || contextString`
DST for HashToScalar():  `DST = "HashToScalar-" || contextString`
where `contextString = "VOPRF06-" || I2OSP(modeBase, 1) || I2OSP(suite.ID, 2)`

Unless I am missing something, we only move `VOPRF06-` to the context string.

**Comment by chris-wood** [comment]
Indeed - closing as resolved. @bytemare please reopen if you disagree with this assessment!
