### ISSUE TITLE
Spec is missing reference to string encoding vector

### ISSUE THREAD

**Issue by FredericJacobs** [cfrg/draft-irtf-cfrg-voprf#271]
I assume it would be ascii but the encoded string format is defined nowhere in the spec.

**Comment by chris-wood** [comment]
@FredericJacobs can you elaborate on this issue? I don't understand what's missing.

**Comment by FredericJacobs** [comment]
The spec doesn't say what string encoding is expected for strings like "Context-" or "Finalize-"

**Comment by chris-wood** [comment]
Ah, gotcha. It's ASCII. I'll clarify.
