### ISSUE TITLE
Input -> Message?

### ISSUE THREAD

**Issue by FredericJacobs** [cfrg/draft-irtf-cfrg-voprf#273]
<img width="183" alt="Screenshot 2021-09-10 at 18 41 04" src="https://user-images.githubusercontent.com/400296/133150547-b7c3b9a5-4f37-4fcf-9fe1-274110b2ffa6.png">

The above is quite confusing to take output as input. 

I'm not really liking the nomenclature of input and output for VOPRFs.

Have you considered other names?

For input, I think `message` could work. For output, I think `evaluationResult` or something, but it might be difficult to not have the name clash with the evaluation function.

**Comment by chris-wood** [comment]
> I'm not really liking the nomenclature of input and output for VOPRFs.

This is, at the end of the day, a PRF, which is just a function with inputs and outputs. We've not bikeshed the names of these yet.

**Comment by chris-wood** [comment]
This function was dropped from the draft, so this is no longer relevant. Closing.
