### ISSUE TITLE
Generalized H3

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#281]
It's possible to extend the POPRF design to build a puncturable variant (in the metadata), a la [STAR](https://arxiv.org/pdf/2109.10074.pdf). Currently, the POPRF abstraction does not allow this to be done so easily. We could probably accommodate it by allowing servers to specify H3, the HashToScalar function used for computing the evaluation context. @alxdavids, thoughts?

**Comment by alxdavids** [comment]
I think this could be useful. Would the choice of H3 be completely open, or would there would be a set of potential choices?

**Comment by chris-wood** [comment]
If anything, I imagine it would be fixed (in this doc) to reasonable choices, namely, random oracles. Though, now that I think more about it, it's not unreasonable to just specify elsewhere how `info` is computed on client and server using the PRF, and then how the result is passed into the existing APIs. So nothing probably needs to happen here. Closing!
