### ISSUE TITLE
Remove input from Finalize DST

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#288]
In Finalize, we include `evaluatedElement` in the hash input, which seems redundant with `input`. We could probably drop `input` from this step, which would simplify the API quite a bit too. Or we could replace it with the representative of `input` in the group (`HashToGroup(input)`).

**Comment by armfazh** [comment]
In principle this is a good idea especially when long inputs are passed to two hash functions (HashToGroup and last Hash).
OTOH, after looking at the [JJK paper](https://eprint.iacr.org/2014/650.pdf), the security proof and any other arguments always consider the client's input to be part of the last hash invocation.
So, I am not really confident about removing the input from the last hash, not sure what is the effect on the security proof.

**Comment by chris-wood** [comment]
Yeah, I no longer think we can just remove it, but we could replace it with its concise representation (i.e., `HashToGroup(input)`).

**Comment by chris-wood** [comment]
Leaving this as-is absent security analysis.
