### ISSUE TITLE
Certified public key

### ISSUE THREAD

**Issue by alxdavids** [cfrg/draft-irtf-cfrg-voprf#29]
In our protocol, the public key is `(G, Y)` where `Y = kG` for the Server's key `k`.

From Hugo:

```
The reason is that when Y is not certified (namely, the client gets it from the
server but cannot verify it - as in OPAQUE settings where the client does not
store Y), there are some "attacks" that we have identified that do not seem to
have a practical effect but suffice to show that the OPRF with additive blinding
does not satisfy our UC definition of OPRF (this is noted in the OPAQUE paper). 
We are working on this now to show that one can weaken the UC functionality to
accept the additive blinding as secure and showing that this definition suffices
for OPAQUE. But we don't have the full results yet. The reason I prefer NOT to
include Y under the hash is that if you do multiplicative blinding in the
non-verifiable case then you don't need Y at all, and if you are in a verifiable
case with certified Y then the "attack" does not work. Still, for the
non-certified Y case and additive blinding, the issue is not fully resolved. For
OPAQUE I was hoping that by the time we standardize on it, we will have a better
understanding of this issue and will be able to eliminate Y under the hash but
now it is a bit premature to have 100% confidence.
```

So I think the way to resolve this is to either specify that `Y` is certified in the additive case, or we could include `Y` in the hash (i.e. compute `H(x,Y,H1(x)^k)`). It's true that we don't need to do this in the multiplicative case so maybe including in the hash is overkill, and we should just go with certification?

@chris-wood for opinion.

**Comment by alxdavids** [comment]
I'm not sure what the best way to tackle this is? It seems like quite an involved change and so maybe we should keep this open for a future issue?

**Comment by chris-wood** [comment]
Sorry for the extreme delay, @alxdavids! I think including `Y` in the hash is a fine path forward. Even in the (non-verifiable) OPRF case, it seems strange to not include some representation of the server's public key. Can we do that?

**Comment by alxdavids** [comment]
Sure, that sounds fine to me. I'll write up the change.
