### ISSUE TITLE
`HashToGroup` and `HashToScalar` can produce invalid keys

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-voprf#305]
`HashToGroup` can produce the identity element and `HashToScalar` can produce a zero scalar. It is extremely unlikely though.

Currently it's not specified how to behave when this happens. Potentially, on failure to produce a valid output, the program might just automatically try again, which would simply be rejection sampling. Maybe that's fine, IANA cryptographer.

In addition `DeriveKeyPair` relies on `HashToScalar`, but it's currently undefined how to handler zero scalars.
```sage
def DeriveKeyPair(mode, suite, seed):
  skS = GG.HashToScalar(seed, DST = "HashToScalar-" || contextString)
  pkS = ScalarBaseMult(skS)
  return skS, pkS
```
https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-08.html#section-2.1-5
> Two functions can be used for generating a (V)OPRF key pair (`skS`, `pkS`)
where `skS` is a non-zero integer less than `p` and `pkS = ScalarBaseMult(skS)`:
`GenerateKeyPair` and `DeriveKeyPair`.

Related: cfrg/draft-irtf-cfrg-opaque#298.

**Comment by chris-wood** [comment]
Let's track this in #307.
