### ISSUE TITLE
Infallible functions

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-voprf#320]
> Even with a password dictionary with entropy of 256 bits, the probability of this happening is 2^{-256}. There are worse things happening at that probability level including guessing OPRF keys, discrete logarithms, signature and encryption keys, multiple collisions, etc. If you get such a case there is a billions of times higher probability that this is due to a programming bug or the break of the underlying hash function. This is why I recommend that if a program finds such a case (a password hashed to the identity element), you output a HUGE ERROR message.

As an implementer I'm still unsure what to do. Sure I can return an error message, but there are still passwords out there that **correctly** map to the identity point, so if this ever happens, there is no action I can take.

> By the way, in the case of OPAQUE with 2HashDH, even if the password is mapped to the identity (a fact that is learned by a passive adversary by seeing H(pw)^r), the attacker (including an active one or even the server itself) needs to run a dictionary attack on the password because the password is hashed together with the group identity. With a 256-bit entropy password this will take 2^255 time. So you could keep running OPAQUE with this password.

For this to happen OPAQUE has to rely on a special version of `Blind` that doesn't return an error on an identity element.

---

This could be easily solved in OPAQUE by making sure the `input` to `Blind` is not simply the password but add a counter to it like was done in `DeriveKeyPair`.

I would like to understand though, why a non-fallible solution like using the reduction mod n-1 plus one method is undesired. It was mentioned before that it's undesirable to require `HashToScalar` or `HashToGroup` to not be able to return a zero scalar or identity element. If that is the problem, `HashToNonZeroScalar` and `HashToNonIdentityPoint` could be introduced for example. But the mod n-1 plus could also simply be added after using `HashToScalar` for example.

I understand that there is not a high motivation to address this as the chances of it occurring are astronomically low.

---

Continuation from https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/307#issuecomment-1024103769.

**Comment by chris-wood** [comment]
Please take this issue to the OPAQUE repo :) This is not something the VOPRF spec can address.

**Comment by chris-wood** [comment]
Oops, I didn't read the bottom half of this issue! (I was perusing on my phone.) Sorry about that.

You ask:

> I would like to understand though, why a non-fallible solution like using the reduction mod n-1 plus one method is undesired. It was mentioned before that it's undesirable to require HashToScalar or HashToGroup to not be able to return a zero scalar or identity element. If that is the problem, HashToNonZeroScalar and HashToNonIdentityPoint could be introduced for example. But the mod n-1 plus could also simply be added after using HashToScalar for example.

The hash-to-group operation is assumed to act like a random map from inputs to _all_ group elements, including the identity element. We [don't currently have an implementation](https://cfrg.github.io/draft-irtf-cfrg-hash-to-curve/draft-irtf-cfrg-hash-to-curve.html) of hash-to-group-excluding-identity, which, as you point out, would address this issue for `Blind`. One could wrap hash-to-group with a counter-like thing to implement it, but I'm not convinced this is worth the complexity for something that happens with negligible probability.

**Comment by daxpedda** [comment]
Specifically I would like to know why the "reduction mod n-1 plus one" method can't be used instead of a counter, which is rejection sampling and not constant-time.

> One could wrap hash-to-group with a counter-like thing to implement it

Indeed, that would have been my suggestion.

> ... I'm not convinced this is worth the complexity for something that happens with negligible probability.

I understand the hesitation:
- For OPAQUE it is important because otherwise specific password can't be used. The chance of that actually occurring is (extremely) low, but not impossible, something that for example a traditional password hash like Argon2 doesn't suffer from.
- A counter is undesirable, besides from being not constant-time, because it would still need to be fallible in the code. This makes auditing harder (a tiny bit) and for example doesn't easily allow for encoding the infallibility of it through the type system. For example, in Rust, one could `panic` instead, but that's even more undesirable. Again, something that Argon2 doesn't suffer from.

I'm very much seeing this from the lens of implementing the OPAQUE protocol in Rust. I would like to provide a non-fallible API to consumers where I can advertise that this can neither panic nor fail otherwise.
When consumers of this library review the error codes, they will find obvious ones, like `PasswordMismatch`, but `ProtocolFailure`, something that will deterministically fail won't look that good when trying to convince people to switch from traditional password hashing to PAKE.

**Comment by chris-wood** [comment]
> I'm very much seeing this from the lens of implementing the OPAQUE protocol in Rust. I would like to provide a non-fallible API to consumers where I can advertise that this can neither panic nor fail otherwise.

Yeah, I understand the motivation here, and I agree that this would be a nice property to advertise to users. However, as you say, even if we went with a counter (or similar) based try-and-increment solution, the code would inherently need to deal with failures, right? I simply don't see a solution right now that would yield an infallible interface.

**Comment by daxpedda** [comment]
> I simply don't see a solution right now that would yield an infallible interface.

The "reduction mod n-1 plus one" method could work.

**Comment by daxpedda** [comment]
@armfazh is the one who pointed this out in https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/298#issuecomment-1006936162.

It's used for example in ECDSA key generation as specified in the [NIST FIPS 186-4](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf#%5B%7B%22num%22%3A152%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C70%2C632%2C0%5D).

**Comment by chris-wood** [comment]
> The "reduction mod n-1 plus one" method could work.

Sorry, maybe I'm not following you here. For OPAQUE, we only care about the OPRF, and the only way that `Blind` can fail is if hash-to-group yields the identity element. What does "reduction mod n-1 plus one" mean in the context of that function?

**Comment by daxpedda** [comment]
Forgive me, the whole time I was thinking of `HashToScalar`, which this applies to, and forgot that we are actually talking about `HashToGroup` here! My bad 😅!

I'm assuming there is no method to coerce an element to a non-identity element?

Alternatively I can think of the following solutions:
- Implement a counter into `Blind`, not ideal as it is still fallible but it's best effort.
- Propose a `HashToNonIdentityElement` to the hash-to-curve spec and see if something comes out of it.

**Comment by daxpedda** [comment]
> > Implement a counter into Blind, not ideal as it is still fallible but it's best effort.
> 
> Wouldn't this still need to fail or panic?

Right, as I said. My assumption here is that, from the lens of OPAQUE again, there are password that will fail for sure here, even if it's unlikely, they exist. A counter would prevent that, for sure, in the sense of there is no password that can fail through the counter. (IANA cryptographer, please call me out if I'm talking nonsense)

> That said, I'll ask some folks (the real experts) if they have any thoughts on how to address this.

That would be amazing. Thank you!

**Comment by chris-wood** [comment]
> Right, as I said. My assumption here is that, from the lens of OPAQUE again, there are password that will fail for sure here, even if it's unlikely, they exist. A counter would prevent that, for sure, in the sense of there is no password that can fail through the counter. (IANA cryptographer, please call me out if I'm talking nonsense)

I'm still not sure I'm following. Let's say one implemented the counter. Surely there must be code that's hit when the counter reaches its limit, right? So how exactly does a counter make the function infallible?

**Comment by daxpedda** [comment]
https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/321 if we can't make `Blind` infallible.

**Comment by chris-wood** [comment]
I don't see how this won't be infallible. Let's assume you have prepend a counter to the input. Let's say further that _every_ prepended input maps to the identity element, perhaps because the hash-to-group function is borked. There's two situations here: either the counter keeps incrementing endlessly, never terminating (bad), or the counter does reach a limit and the function stops. In the latter case, you'd fail. 

What am I missing?

**Comment by daxpedda** [comment]
Yes!

**Comment by daxpedda** [comment]
I'm starting to have doubts about my english, I kept saying it's **not** infallible, am I using a wrong expression or something? 😄

**Comment by daxpedda** [comment]
My assumption (I might be wrong, IANA cryptographer), is that a counter would make it "actually" infallible, just not in code. But if all it does is only decrease the already astronomically small chance that it would fail, then of course it's pointless.

**Comment by chris-wood** [comment]
> But if all it does is only decrease the already astronomically small chance that it would fail, then of course it's pointless.

Right, this is my take =)

**Comment by daxpedda** [comment]
Alright. So the only option left is to hope that we can come up with a truly infallible solution.

**Comment by chris-wood** [comment]
No problem -- thanks for the discussion!

**Comment by armfazh** [comment]
> The "reduction mod n-1 plus one" method could work.

Yes, it works; however, this will require new code for performing reductions modulo `n-1`.

**Comment by armfazh** [comment]
> Alright. So the only option left is to hope that we can come up with a truly infallible solution.


Instead of increasing a counter, one can derive a new one through, for example, iterated hashing.

```js
1. function foo(input) {
2.   C = 0
3.   while true {
4.     P = HashToGroup(input || C)
5.     if P != G.Identity()
6.       return P
7.     C = Hash(C)
8.   }
9. }  
```

This approach has the disadvantage that it can run endlessly, which could be a target for attackers or when HashToGroup is broken.

**Comment by chris-wood** [comment]
@armfazh this is still another instance of the try-and-increment approach, correct? It either must terminate after a certain number of iterations, or it must provably yield a non-identity element. We don't have (b), and (a) implies that the function is fallible. As you point out, we can't specify non-terminating behavior. And since this doesn't change the resulting failure probability -- it's still negligible -- I'm struggling to see why it's an improvement.

**Comment by armfazh** [comment]
Yes, that code is just another try-and-increment method. 
Not claiming superiority, only mentioned that the code snippet don't fail (unless something is broken) in response to the quest for an _infalible solution_.

**Comment by chris-wood** [comment]
> Yes, that code is just another try-and-increment method. 
> 
> Not claiming superiority, only mentioned that the code snippet don't fail (unless something is broken) in response to the quest for an _infalible solution_. 
> 
> 

Well, as has been discussed in this thread, there's two outcomes for a try-and-increment approach: (1) the function terminates only when it finds a valid value, or (2) the function terminates after a certain number of iterations. 

I think we all agree that (2) means the function must be fallible, whereas (1) is, in theory, not fallible. However, importantly, it is possible for (1) to not terminate in pathological cases or e.g. where the underling hash function is broken. Certainly a function shouldn't endlessly loop, so any actual implementation will stop iteration after a certain amount of tries. And in that case, I claim the implementation of (1) effectively yields something close to (2), which is fallible.

**Comment by armfazh** [comment]
it seems the consensus is that even adding a counter-based or a try-and-increment approach to avoid fallible cases, all what it does is to reduce the **already negligible** probability that these cases occur in practice.

Also, it is ok to avoid try-and-error approaches that do not terminate after a deterministic number of steps. Otherwise, an implementation can loop forever, without returning an error.

The current document now includes a section that describes the errors that could appear with negligible probability, and when if ever happen, the protocol stops.

**Comment by chris-wood** [comment]
Agreed. Closing without resolution, as we already note this is an exceptional case that occurs with negligible probability.
