### ISSUE TITLE
Introduce a counter to `Blind`

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-voprf#321]
Currently some inputs exist that can't be used in `Blind` because they could yield the identity element through `HashToGroup`. One solution to this problem could be to introduce a counter, like in `DeriveKeyPair`.

From #320.

**Comment by chris-wood** [comment]
This doesn't solve the problem. It just makes the (already negligible) probability of failure smaller.

**Comment by daxpedda** [comment]
> This doesn't solve the problem. It just makes the (already negligible) probability of failure smaller.

As discussed in #320, this is pointless.
