### ISSUE TITLE
Add pointers to proven constructions

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#335]
The [crypto review panel feedback](https://mailarchive.ietf.org/arch/msg/crypto-panel/QXC3drh1hs-XGkXyjwyCj_pFNNI/) pointed out that there's a missing link between the different constructions in the draft and the papers in which they were proven secure. After offline exchanges with @vkumar-qc, adding these links would resolve the issue, so this issue tracks that.

**Comment by chris-wood** [comment]
@armfazh or @alxdavids, is this something one of you can take?

**Comment by armfazh** [comment]
I can take this, just let me know what are the specific comments given offline.

**Comment by chris-wood** [comment]
Thanks! We should also be sure to note differences between what was in these papers and what's done here. For example, I think the DLEQ proof in the original privacy pass paper included the group generator in the transcript, but we don't do that here. There might be other small differences too, but I don't recall them offhand.

**Comment by armfazh** [comment]
Refer to #344 for updates on this ticket.
