### ISSUE TITLE
Comments in Kumar's review

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#340]
Tracking issues raised in [review](https://mailarchive.ietf.org/arch/msg/crypto-panel/QXC3drh1hs-XGkXyjwyCj_pFNNI/)

> Major comments:
>   1.  2.1 on page 9 says "This function can raise a DeserializeError if deserialization fails or A is the identity element of the group": This implies that if I serialize and then serialize the identity element, I will get an error!

Tracked in #342 

>   2.  2.2 on page 10 says "... proving that the discrete log of two values is identical in zero knowledge" without ever defining discrete log and zero knowledge proofs. The authors say that their construction is built on Chaum-Pedersen proof, but no further details are provided.

Fixed in #336 

>   3.  2.2.1 on page 11 has statements like Cs = [C], Ds = [D] without explaining what square brackets [ ] actually mean.

TODO: Tracked in #297 

>   4.  2.2.1 on page 11 ends the description of GenerateProof without ever describing why the output of the function [c , s] is a discrete log equivalence proof and why is it zero knowledge.

Fixed in #336 

> Minor comments:
>   1.  1.3 on page 7: object x --> byte array x

Already fixed.

>   2.  1.3 on page 7: Better to separate I2SOP and OS2IP, because the current description might be taken to suggest that I2SOP converts a byte array to a non-negative integer, which according to RFC 8017 is just the opposite, i.e., converts a non-negative integer to a byte array.

Fixed in #338 

>   3.  1.3 on page 8 says "String values such as "Finalize" are ASCII string literals": It would be good to have all the strings mentioned here not just an example.

Fixed in #339 and #346

>   4.  2 on page 8: Redundant long at the end of this sentence "A cryptographic hash function whose output length is Nh bytes long".

Fixed in #338 

>   5.  2.1 on page 8 starts talking about groups and then suddenly mentions finite fields without explaining what they are. It becomes clear reading further down that the authors need them for scalars. It would have been less confusing if they simply used the set of integers {0, 1, ..., p-1}.

Fixed in #336 

>   6.  2.1 on page 9 says "... multiplicative inverse of input Scalar s modulo ...". This is the first time modulo operation is mentioned.

Fixed in #338

**Comment by chris-wood** [comment]
@armfazh if possible could you please give an update on this issue?

**Comment by armfazh** [comment]
The remaining issues are:
 - #342 This is easy to fix, (I will prepare a PR, coming today-ish).
 - #297 This needs a bit of more refactor on the document. No big changes tough. I will work on a proposal for this issue this week, and want also hear other alternatives.
 
The other points in the review have been already addressed.

**Comment by armfazh** [comment]
This ticket has all the listed issues addressed/resolved now.
