### ISSUE TITLE
Better explain the batching API used in DLEQ proof 

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#341]
From [review](https://mailarchive.ietf.org/arch/msg/crypto-panel/QXC3drh1hs-XGkXyjwyCj_pFNNI/)

> 2.2.1 on page 11 has statements like Cs = [C], Ds = [D] without explaining what square brackets [ ] actually mean.

**Comment by chris-wood** [comment]
This is related to #297.
