### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#342]
From [review](https://mailarchive.ietf.org/arch/msg/crypto-panel/QXC3drh1hs-XGkXyjwyCj_pFNNI/)

> 2.1 on page 9 says "This function can raise a DeserializeError if deserialization fails or A is the identity element of the group": This implies that if I serialize and then serialize the identity element, I will get an error!

**Comment by armfazh** [comment]
I consider the current text is correct, that is deserialization must fail both due to an encoding error, _AND_ when the point is the identity element.

**Comment by chris-wood** [comment]
Yep, I agree. We can resolve this by noting this feature when we describe the serialization function. Would that work?

**Comment by armfazh** [comment]
On a second thought, I think the focus for invalid input must be explicit in the `Input validation` section, rather than on deserialization.

See my proposal in #343 .
