### ISSUE TITLE
Section 7.2.3-3 references old cipher suite ID

### ISSUE THREAD

**Issue by tmthrgd** [cfrg/draft-irtf-cfrg-voprf#377]
This section contains references to the pre-draft-v17 cipher suite IDs rather than the newer identifiers:

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/8e9121f0976b0ba5dce93495c9c5c66ca9215436/draft-irtf-cfrg-voprf.md?plain=1#L1719-L1720

**Comment by chris-wood** [comment]
Thank you! Addressed in #378.

**Comment by tmthrgd** [comment]
@chris-wood No worries. 🙂 I’ll close this as #378 has merged.
