### ISSUE TITLE
DeriveKeyPair DST prefix differs from others

### ISSUE THREAD

**Issue by tmthrgd** [cfrg/draft-irtf-cfrg-voprf#382]
I'm not sure if it's worth correcting at this point in the standardization process, but when implementing, I noticed that `"DeriveKeyPair"` is the only string concatenated to `contextString` without a separating dash (`-`).

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/002ca6a8809186692984863cbb897bee1501abda/draft-irtf-cfrg-voprf.md?plain=1#L764

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/002ca6a8809186692984863cbb897bee1501abda/draft-irtf-cfrg-voprf.md?plain=1#L1260

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/002ca6a8809186692984863cbb897bee1501abda/draft-irtf-cfrg-voprf.md?plain=1#L1263

https://github.com/cfrg/draft-irtf-cfrg-voprf/blob/002ca6a8809186692984863cbb897bee1501abda/draft-irtf-cfrg-voprf.md?plain=1#L499

**Comment by chris-wood** [comment]
Yeah, given (1) that we've locked in the test vectors for the final version and (2) the key generation mechanism can always be updated separately if desired, I don't think we should change this. Thanks for flagging the issue. If this document is updated in the future, we'll keep this on the list of things to possibly update.
