### ISSUE TITLE
seed size is 32 or Ns bytes?

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#384]
> There appears to be a small discrepancy in the seed size used in the draft.
> Ns is defined in Section 2.1, as the fixed length scalar size encoding for a curve.
> Ns is used in Section 3.2.1 Deterministic Key Generation as the input of the seed[Ns].
> However, your test vectors use a fixed 32-byte seed size.

Test vectors use 32-fixed size, while document recommends a size depending on the base field.

**Comment by armfazh** [comment]
@chris-wood here are two options:
1) update the text to set `Ns=32` for all cases. This avoids to recalculate test vectors.
2) set Ns correctly in the test vectors.
which would be the one to pursue?

**Comment by chris-wood** [comment]
I don't think either is acceptable at this point. I think the best we can do is note that the test vectors deviated from `Ns` and used 32.

**Comment by juhesse** [comment]
@armfazh @chris-wood In the alternative DeriveKeyPair method in Section 3.2.1, the random seed of length Ns is the only entropy that goes into the OPRF key (DeriveKeyPair function). If you set that to 32 fixed, the security level of the OPRF will be upper bound by 32. This is significantly lower than key derivation through RandomScalar(). Can you explain for which applications such an OPRF implementation would be suitable? Currently the draft says "can use either" method, and I cannot find further guidance.

**Comment by chris-wood** [comment]
> If you set that to 32 fixed, the security level of the OPRF will be upper bound by 32. This is significantly lower than key derivation through RandomScalar()

Sure, it may be significantly lower, but the security bound is large enough in all cases that this difference does not matter. 32 bytes of entropy will always be enough -- we don't need anything more.

**Comment by juhesse** [comment]
I was talking about a security level of 32 bits, which seems insufficient to me ;) 

Let's see where this confusion comes from. Section 2.1 sets Ns to be the length of the *byte* array. E.g., for a group of size 256, Ns will be 32. Then DeriveKeyPair in Section 3.2.1 uses it as "seed[Ns]", and from what you write, this function seed[] should interpret its input in terms of bytes, not bits as I thought. 

Ok, I read it now in the first paragraph of 3.2.1:  "It accepts a seed of Ns bytes generated..." - If this is not super standard notation for RFCs I would recommend making that clear by formally defining this seed function.

Thank you for clarifying, Chris! And to answer the original question, it seems fine to me to set the seed entropy to 32 *bytes* fixed.

**Comment by chris-wood** [comment]
No problem. =)

**Comment by chris-wood** [comment]
Closing as resolved.
