### ISSUE TITLE
How long are the serialized byte arrays?

### ISSUE THREAD

**Issue by jyasskin** [cfrg/draft-irtf-cfrg-voprf#386]
https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-21.html#name-online-protocol says

> Elements and scalars are serialized to byte arrays

but doesn't say how long the arrays are. I suspect the lengths are implied by the ciphersuite, but it would be good to say it explicitly so that implementers are sure to pick the same lengths.

**Comment by armfazh** [comment]
[Section 2.1](https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-21.html#name-prime-order-group) already explains that: the size of elements is the constant `Ne` and the size of scalars is the constant `Ns`.

Also, each ciphersuite define the value of these constant values.

**Comment by armfazh** [comment]
Closing as answered.
