### ISSUE TITLE
Improve VOPRF API

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#76]
PrivacyPass, for example, requires clients to run Setup() and use its results, somehow. There isn't currently a clean API one can use for operating on this private key. We should spend some time here to make integration into other protocols simpler.

**Comment by alxdavids** [comment]
I think this is likely to be addressed in #91

**Comment by chris-wood** [comment]
OPAQUE needs the following APIs:

- GenerateScalar()
- Blind(x)
- Evaluate(k, M)
- Unblind(r, Z)
- Finalize(x, N, dst)
- Serialize(x)
- Decode(enc)

We don't have GenerateScalar(). I'll add that.

**Comment by alxdavids** [comment]
Would there be any room in OPAQUE to rename `GenerateKeyPair` to `KeyGen`? This is mostly because I think this is a nicer name, so no worries if not.

**Comment by chris-wood** [comment]
Yeah, that works for me.
