### ISSUE TITLE
Specify Serialize/Deserialize APIs

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-voprf#77]
This will make integration in PrivacyPass (and elsewhere) much easier. For example, rather than say "parse these opaque bytes and turn them into curve points," for example, we can say "element = Deserialize(bytes)." In general, the more we can hide curve details from higher-level documents, the better.

**Comment by armfazh** [comment]
Agree, each group must specify how to encode/decode group elements into binary strings.
