### ISSUE TITLE
Unifies the name of actors V and P to longer names

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#80]
V and P refer to the participants of a zero-knowledge proofs. Consider give a more familiar name to this actors, Verifier/Prover, Victor/Peggy

**Comment by alxdavids** [comment]
I think expanding to their full titles is fine. I'm personally against using human names for protocol participants, but I'm willing to reconsider if it is believed that is a much better way of representing them.
