### ISSUE TITLE
Unify DLEQ for n>=1 or n>=0.

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#85]
I was curious if there is a way to unify the description of DLEQ for n>=1, or even for n>=0.
If this will be possible, we end up with a single set of algorithms, so a shorter description.

**Comment by alxdavids** [comment]
We could unify the algorithms, but the specific DLEQ algorithm for n=1 is much more efficient than running batched DLEQ for n>=1. So it depends if we want to preserve that efficiency in the n=1 case. I agree that unifying for simplicity's sake would be nice.

**Comment by armfazh** [comment]
One way to unify is avoiding the calculation of the scalar multiplication by c1.

**Comment by alxdavids** [comment]
Hmmm good idea, we could also just set `c1 = 1` in the n=1 case. Let me investigate further.
