### ISSUE TITLE
Allowing blinding variants?

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-voprf#86]
the document mentioned two blinding methods: rH1(x) and rG+H1(x). 
However, it wasn't mentioned which one to use at suite level.

**Comment by chris-wood** [comment]
@armfazh is that something we need to bake into a suite? I'm not so sure. It seems like an implementation detail to me.

**Comment by armfazh** [comment]
My understanding is that defining a suite implies test vectors, which implies that everyone must follow the same procedure.
So, almost every variant in the construction introduces a parameter in the suite.

**Comment by alxdavids** [comment]
The test vectors for the output of the protocol do not depend on the blinding method. However, the test vectors for the proof values will be different as they are evaluated over whatever the client sends. 

I would rather not state the blinding method as part of the suite though. I think it may be better to also implement fixed-base blinding as part of the suite, and then specify proof values for both blinding types.

**Comment by armfazh** [comment]
That means the proof must encode which blinding is used ?

**Comment by alxdavids** [comment]
(originally thought that I had replied by email, but it seems that it didn't make it here)

No, the proof test vector values will change because the client inputs will change.

**Comment by armfazh** [comment]
I got it now. The blinding method is orthogonal to the suite used.

**Comment by alxdavids** [comment]
Okay, I'm going to close this as its an implementation detail.
